openapi: 3.0.0
info:
  title: BeerBank API
  version: 1.0.0
  description: 'API for BeerBank app.  '
servers:
  - url: 'https://auzaezwlkxrksusuffcq.supabase.co/rest/v1'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: apikey
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    User:
      type: object
      properties:
        user_id:
          type: string
          format: uuid
        nickname:
          type: string
          maxLength: 15
        ex_total:
          type: integer
          default: 0
        balance:
          type: integer
          default: 0
        conversion_rate:
          type: integer
          minimum: 1
          default: 1
    UserPost:
      type: object
      required:
        - user_id
      properties:
        user_id:
          type: string
          format: uuid
        nickname:
          type: string
          maxLength: 15
    UserPatch:
      type: object
      properties:
        conversion_rate:
          type: integer
          minimum: 1
        balance:
          type: integer
    ExerciseEvent:
      type: object
      required:
        - user_id
        - ex_amount
        - ex_time
        - client_event_id
      properties:
        user_id:
          type: string
          format: uuid
        ex_amount:
          type: integer
          minimum: 1
        ex_time:
          type: string
          format: date-time
        client_event_id:
          type: string
          format: uuid
    ExerciseEventStats:
      type: object
      properties:
        user_id:
          type: string
          format: uuid
        ex_time:
          type: string
          format: date-time
        ex_amount:
          type: integer
          minimum: 1
    SpendEvent:
      type: object
      required:
        - user_id
        - spend_amount
        - spend_time
        - client_event_id
      properties:
        user_id:
          type: string
          format: uuid
        spend_amount:
          type: integer
          minimum: 1
        spend_time:
          type: string
          format: date-time
        client_event_id:
          type: string
          format: uuid
    SpendEventStats:
      type: object
      properties:
        user_id:
          type: string
          format: uuid
        spend_time:
          type: string
          format: date-time
        spend_amount:
          type: integer
          minimum: 1
security:
  - ApiKeyAuth: []
  - BearerAuth: []
paths:
  /users:
    get:
      summary: Get current user data
      description: ''
      responses:
        '200':
          description: User data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Create user
      description: Creates a new user after first login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserPost'
            example:
              user_id: '{{user_id}}'
              nickname: hophead
      responses:
        '201':
          description: User created
    patch:
      summary: Update user
      description: 'Updates conversion_rate or balance, filtered by user_id'
      parameters:
        - name: user_id
          in: query
          required: true
          description: Supabase eq filter
          schema:
            type: string
          example: 'eq.{{user_id}}'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserPatch'
            example:
              conversion_rate: 2
      responses:
        '200':
          description: User updated
  /exercise_events:
    post:
      summary: Add exercise event
      description: Logs a new exercise session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExerciseEvent'
            example:
              user_id: '{{user_id}}'
              ex_amount: 10
              ex_time: '2026-03-27T12:00:00Z'
              client_event_id: '{{client_event_id}}'
      responses:
        '201':
          description: Exercise event added
    get:
      summary: Get exercise events
      operationId: ''
      description: Returns exercise sessions for statistics
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: string
          example: 'eq.{{user_id}}'
        - name: order
          in: query
          schema:
            type: string
          example: ex_time.desc
        - name: limit
          in: query
          schema:
            type: integer
          example: 5
        - name: select
          in: query
          schema:
            type: string
          example: 'user_id,ex_time,ex_amount'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExerciseEventStats'
  /spend_events:
    post:
      summary: Add spend event
      description: Logs balance spending event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpendEvent'
            example:
              user_id: '{{user_id}}'
              spend_amount: 50
              spend_time: '2026-03-27T12:00:00Z'
              client_event_id: '{{client_event_id}}'
      responses:
        '201':
          description: Spend event added
    get:
      summary: Get spend events
      description: Returns spendings for statistics
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: string
          example: 'eq.{{user_id}}'
        - name: order
          in: query
          schema:
            type: string
          example: spend_time.desc
        - name: limit
          in: query
          schema:
            type: integer
          example: 5
        - name: select
          in: query
          schema:
            type: string
          example: 'user_id,spend_time,spend_amount'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SpendEventStats'